### ISSUE TITLE
Add the Prowler UI Environment Variables

### ISSUE THREAD

**Issue by petersellars** [petersellars/cloud_security#4]
Add the environment variables for the UI prowler container defined here:
https://github.com/prowler-cloud/prowler/blob/master/docker-compose.yml

```
  ui:
    image: prowlercloud/prowler-ui:${PROWLER_UI_VERSION:-stable}
    env_file:
      - path: .env
        required: false
    ports:
      - ${UI_PORT:-3000}:${UI_PORT:-3000}
 ```

With these env values from here:
https://github.com/prowler-cloud/prowler/blob/master/.env

```
#### Prowler UI Configuration ####
PROWLER_UI_VERSION="stable"
AUTH_URL=http://localhost:3000
API_BASE_URL=http://prowler-api:8080/api/v1
NEXT_PUBLIC_API_DOCS_URL=http://prowler-api:8080/api/v1/docs
AUTH_TRUST_HOST=true
UI_PORT=3000
# openssl rand -base64 32
AUTH_SECRET="N/c6mnaS5+SWq81+819OrzQZlmx1Vxtp/orjttJSmw8="
```

Check that we can hit the UI and check the logs

Learn how to use environment values with Score
See here: https://github.com/score-spec/score-compose/tree/main/examples/02-environment
